// .vitepress/components/GlowNode.vue
<script setup lang="ts">
interface GlowNodeProps {
  label: string
  icon?: string
  size?: 'sm' | 'md' | 'lg'
}

const props = withDefaults(defineProps<GlowNodeProps>(), {
  size: 'md'
})

const sizeClasses: Record<string, string> = {
  sm: 'px-2 py-1 text-xs',
  md: 'px-4 py-2 text-sm',
  lg: 'px-6 py-3 text-base'
}
</script>

<template>
  <div
    class="glow-node inline-flex items-center gap-2 rounded-full border border-primary/40 bg-gray-900 text-white animate-pulse-glow"
    :class="sizeClasses[props.size]"
  >
    <span v-if="props.icon" :class="props.icon" aria-hidden="true"></span>
    <span>{{ props.label }}</span>
  </div>
</template>

<style scoped>
.glow-node {
  box-shadow: 0 0 8px rgba(0, 255, 170, 0.3), 0 0 16px rgba(0, 255, 170, 0.1);
}

@media (prefers-reduced-motion: reduce) {
  .glow-node {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
  }
}
</style>

// src/components/GlowNode.tsx
import React from 'react';

interface GlowNodeProps {
  label: string;
  icon?: string;
  size?: 'sm' | 'md' | 'lg';
}

const sizeStyles: Record<'sm' | 'md' | 'lg', React.CSSProperties> = {
  sm: { padding: '0.25rem 0.5rem', fontSize: '0.75rem' },
  md: { padding: '0.5rem 1rem', fontSize: '0.875rem' },
  lg: { padding: '0.75rem 1.5rem', fontSize: '1rem' },
};

// Preserve class names for test compatibility and external CSS overrides
const sizeClasses: Record<'sm' | 'md' | 'lg', string> = {
  sm: 'px-2 py-1 text-xs',
  md: 'px-4 py-2 text-sm',
  lg: 'px-6 py-3 text-base',
};

export default function GlowNode({ label, icon, size = 'md' }: GlowNodeProps) {
  const style: React.CSSProperties = {
    borderRadius: '9999px',
    boxShadow: '0 0 8px rgba(0,255,170,0.4)',
    animationName: 'pulse-glow',
    animationDuration: '2s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
    willChange: 'box-shadow',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    border: '1px solid rgba(0,255,170,0.3)',
    color: 'var(--color-text, #ffffff)',
    background: 'var(--color-bg-soft, #111827)',
    ...sizeStyles[size],
  };

  return (
    <span className={`glow-node ${sizeClasses[size]}`} style={style}>
      {icon && <span className={`glow-node__icon ${icon}`} aria-hidden="true" />}
      <span className="glow-node__label">{label}</span>
    </span>
  );
}
