// src/components/ArchDiagram.tsx
import React, { useState, useMemo, useCallback, useRef, useEffect } from 'react';

// === Public Types (exported for consumers) ===

export interface NodeDef {
  id: string;
  label: string;
  layer: string;
}

export interface ConnectionDef {
  from: string;
  to: string;
}

export interface LayerDef {
  key: string;
  label: string;
}

export interface ArchDiagramProps {
  /** Whether hover interactions are enabled. Default: true */
  interactive?: boolean;
  /** Node definitions. Default: RAGFlow architecture nodes */
  nodes?: NodeDef[];
  /** Connection definitions. Default: RAGFlow connections */
  connections?: ConnectionDef[];
  /** Layer definitions (order determines layout). Default: RAGFlow layers */
  layers?: LayerDef[];
  /** Accessible label for the diagram. Default: "RAGFlow 系统架构图" */
  ariaLabel?: string;
}

// === Default Data (RAGFlow architecture) ===

const defaultNodes: NodeDef[] = [
  { id: 'webui', label: 'Web UI', layer: 'user' },
  { id: 'api', label: 'API Server', layer: 'service' },
  { id: 'es', label: 'Elasticsearch', layer: 'storage' },
  { id: 'mysql', label: 'MySQL', layer: 'storage' },
  { id: 'minio', label: 'MinIO', layer: 'storage' },
  { id: 'redis', label: 'Redis', layer: 'storage' },
];

const defaultConnections: ConnectionDef[] = [
  { from: 'webui', to: 'api' },
  { from: 'api', to: 'es' },
  { from: 'api', to: 'mysql' },
  { from: 'api', to: 'minio' },
  { from: 'api', to: 'redis' },
];

const defaultLayers: LayerDef[] = [
  { key: 'user', label: '用户层' },
  { key: 'service', label: '服务层' },
  { key: 'storage', label: '存储层' },
];

// === Helper: build adjacency map ===

function buildAdjacencyMap(
  nodeList: NodeDef[],
  connList: ConnectionDef[],
): Record<string, Set<string>> {
  const map: Record<string, Set<string>> = {};
  for (const node of nodeList) {
    map[node.id] = new Set([node.id]);
  }
  for (const conn of connList) {
    map[conn.from]?.add(conn.to);
    map[conn.to]?.add(conn.from);
  }
  return map;
}

// === SVG Connection Line Coordinates ===

interface LineCoords {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export default function ArchDiagram({
  interactive = true,
  nodes = defaultNodes,
  connections = defaultConnections,
  layers = defaultLayers,
  ariaLabel = 'RAGFlow 系统架构图',
}: ArchDiagramProps) {
  const [hoveredNodeId, setHoveredNodeId] = useState<string | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const nodeRefs = useRef<Record<string, HTMLSpanElement | null>>({});
  const [lineCoords, setLineCoords] = useState<Record<string, LineCoords>>({});

  // Build adjacency map (memoized on data changes)
  const adjacencyMap = useMemo(
    () => buildAdjacencyMap(nodes, connections),
    [nodes, connections],
  );

  const connectedSet = useMemo<Set<string> | null>(
    () => (hoveredNodeId ? adjacencyMap[hoveredNodeId] ?? null : null),
    [hoveredNodeId, adjacencyMap],
  );

  const getNodeOpacity = useCallback(
    (nodeId: string): number => {
      if (!interactive || !connectedSet) return 1;
      return connectedSet.has(nodeId) ? 1 : 0.3;
    },
    [interactive, connectedSet],
  );

  const getConnectionOpacity = useCallback(
    (conn: ConnectionDef): number => {
      if (!interactive || !hoveredNodeId) return 1;
      return (conn.from === hoveredNodeId || conn.to === hoveredNodeId) ? 1 : 0.3;
    },
    [interactive, hoveredNodeId],
  );

  const handleMouseEnter = useCallback(
    (nodeId: string) => { if (interactive) setHoveredNodeId(nodeId); },
    [interactive],
  );

  const handleMouseLeave = useCallback(
    () => { if (interactive) setHoveredNodeId(null); },
    [interactive],
  );

  // Measure node positions and compute SVG line coordinates
  useEffect(() => {
    function updateLines() {
      const container = containerRef.current;
      if (!container) return;

      const containerRect = container.getBoundingClientRect();
      const newCoords: Record<string, LineCoords> = {};

      for (const conn of connections) {
        const fromEl = nodeRefs.current[conn.from];
        const toEl = nodeRefs.current[conn.to];
        if (!fromEl || !toEl) continue;

        const fromRect = fromEl.getBoundingClientRect();
        const toRect = toEl.getBoundingClientRect();

        newCoords[`${conn.from}-${conn.to}`] = {
          x1: fromRect.left + fromRect.width / 2 - containerRect.left,
          y1: fromRect.top + fromRect.height / 2 - containerRect.top,
          x2: toRect.left + toRect.width / 2 - containerRect.left,
          y2: toRect.top + toRect.height / 2 - containerRect.top,
        };
      }

      setLineCoords(newCoords);
    }

    // Initial measurement after layout
    const timer = setTimeout(updateLines, 50);

    // Re-measure on resize
    const observer = typeof ResizeObserver !== 'undefined'
      ? new ResizeObserver(updateLines)
      : null;
    if (observer && containerRef.current) {
      observer.observe(containerRef.current);
    }

    return () => {
      clearTimeout(timer);
      observer?.disconnect();
    };
  }, [connections, nodes, layers]);

  // Determine if we have computed coordinates (SSR/test env may not have DOM measurements)
  const hasCoords = Object.keys(lineCoords).length > 0;

  return (
    <div
      ref={containerRef}
      role="img"
      aria-label={ariaLabel}
      className="arch-diagram"
      style={{
        display: 'flex',
        flexDirection: 'row',
        gap: '2rem',
        alignItems: 'flex-start',
        justifyContent: 'center',
        padding: '1.5rem',
        width: '100%',
        position: 'relative',
      }}
    >
      {layers.map((layer) => {
        const layerNodes = nodes.filter((n) => n.layer === layer.key);
        return (
          <div
            key={layer.key}
            className="arch-diagram__layer"
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: '0.75rem',
              flex: 1,
            }}
          >
            <span
              className="arch-diagram__layer-label"
              style={{
                fontSize: '0.75rem',
                color: 'var(--color-text-muted, #9ca3af)',
                fontWeight: 600,
                marginBottom: '0.5rem',
              }}
            >
              {layer.label}
            </span>
            {layerNodes.map((node) => (
              <span
                key={node.id}
                ref={(el) => { nodeRefs.current[node.id] = el; }}
                data-node-id={node.id}
                className="arch-diagram__node"
                onMouseEnter={() => handleMouseEnter(node.id)}
                onMouseLeave={handleMouseLeave}
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  padding: '0.5rem 1rem',
                  borderRadius: '9999px',
                  boxShadow: '0 0 8px rgba(0,255,170,0.4)',
                  border: '1px solid rgba(0,255,170,0.3)',
                  fontSize: '0.875rem',
                  color: 'var(--color-text, #ffffff)',
                  background: 'var(--color-bg-soft, #111827)',
                  opacity: getNodeOpacity(node.id),
                  transition: 'opacity 300ms ease',
                  cursor: interactive ? 'pointer' : 'default',
                }}
              >
                {node.label}
              </span>
            ))}
          </div>
        );
      })}

      {/* SVG connections — rendered when DOM measurements are available */}
      {hasCoords && (
        <svg
          className="arch-diagram__svg-connections"
          aria-hidden="true"
          style={{
            position: 'absolute',
            inset: 0,
            width: '100%',
            height: '100%',
            pointerEvents: 'none',
            overflow: 'visible',
          }}
        >
          {connections.map((conn) => {
            const coords = lineCoords[`${conn.from}-${conn.to}`];
            if (!coords) return null;
            return (
              <line
                key={`${conn.from}-${conn.to}`}
                data-from={conn.from}
                data-to={conn.to}
                className="arch-diagram__connection"
                x1={coords.x1}
                y1={coords.y1}
                x2={coords.x2}
                y2={coords.y2}
                stroke="rgba(0,255,170,0.4)"
                strokeWidth="2"
                strokeDasharray="8 6"
                strokeLinecap="round"
                style={{
                  opacity: getConnectionOpacity(conn),
                  transition: 'opacity 300ms ease',
                }}
              />
            );
          })}
        </svg>
      )}

      {/* Fallback: text-based connections for environments without layout (SSR, tests) */}
      {!hasCoords && (
        <div className="arch-diagram__connections-list" aria-hidden="true">
          {connections.map((conn) => (
            <span
              key={`${conn.from}-${conn.to}`}
              data-from={conn.from}
              data-to={conn.to}
              className="arch-diagram__connection"
              style={{
                opacity: getConnectionOpacity(conn),
                transition: 'opacity 300ms ease',
                fontSize: '0.7rem',
                color: 'var(--color-brand, #00ffaa)',
                whiteSpace: 'nowrap',
              }}
            >
              {(nodes.find((n) => n.id === conn.from)?.label ?? conn.from)} →{' '}
              {(nodes.find((n) => n.id === conn.to)?.label ?? conn.to)}
            </span>
          ))}
        </div>
      )}
    </div>
  );
}

// .vitepress/components/ArchDiagram.vue
<script setup lang="ts">
/**
 * RAGFlow system architecture interactive diagram.
 * Layered layout: User layer (Web UI) → Service layer (API) → Storage layer (ES, MySQL, MinIO, Redis)
 * Uses GlowNode for nodes and FlowLine for connections with directional arrows.
 * Responsive: vertical on mobile (<768px), horizontal on desktop (>=768px).
 */
import { ref } from 'vue'
import GlowNode from './GlowNode.vue'
import FlowLine from './FlowLine.vue'

interface ArchDiagramProps {
  interactive?: boolean
}

const props = withDefaults(defineProps<ArchDiagramProps>(), {
  interactive: true
})

interface NodeDef {
  id: string
  label: string
  layer: 'user' | 'service' | 'storage'
}

interface ConnectionDef {
  from: string
  to: string
}

const nodes: NodeDef[] = [
  { id: 'webui', label: 'Web UI', layer: 'user' },
  { id: 'api', label: 'API Server', layer: 'service' },
  { id: 'es', label: 'Elasticsearch', layer: 'storage' },
  { id: 'mysql', label: 'MySQL', layer: 'storage' },
  { id: 'minio', label: 'MinIO', layer: 'storage' },
  { id: 'redis', label: 'Redis', layer: 'storage' },
]

const connections: ConnectionDef[] = [
  { from: 'webui', to: 'api' },
  { from: 'api', to: 'es' },
  { from: 'api', to: 'mysql' },
  { from: 'api', to: 'minio' },
  { from: 'api', to: 'redis' },
]

const hoveredNode = ref<string | null>(null)

function onNodeEnter(nodeId: string) {
  if (props.interactive) {
    hoveredNode.value = nodeId
  }
}

function onNodeLeave() {
  hoveredNode.value = null
}

function isNodeHighlighted(nodeId: string): boolean {
  if (!hoveredNode.value) return true
  if (nodeId === hoveredNode.value) return true
  return connections.some(
    (c) =>
      (c.from === hoveredNode.value && c.to === nodeId) ||
      (c.to === hoveredNode.value && c.from === nodeId)
  )
}

function isConnectionHighlighted(conn: ConnectionDef): boolean {
  if (!hoveredNode.value) return true
  return conn.from === hoveredNode.value || conn.to === hoveredNode.value
}

function getNodeOpacity(nodeId: string): number {
  if (!hoveredNode.value) return 1
  return isNodeHighlighted(nodeId) ? 1 : 0.3
}

function getConnectionOpacity(conn: ConnectionDef): number {
  if (!hoveredNode.value) return 1
  return isConnectionHighlighted(conn) ? 1 : 0.3
}

const layers = [
  { id: 'user', label: '用户层' },
  { id: 'service', label: '服务层' },
  { id: 'storage', label: '存储层' },
]

function getNodesByLayer(layerId: string): NodeDef[] {
  return nodes.filter((n) => n.layer === layerId)
}

// Get connections going from a layer to the next
function getConnectionsFromLayer(layerId: string): ConnectionDef[] {
  const layerNodeIds = getNodesByLayer(layerId).map((n) => n.id)
  return connections.filter((c) => layerNodeIds.includes(c.from))
}
</script>

<template>
  <div class="arch-diagram" role="img" aria-label="RAGFlow 系统架构图">
    <!-- Desktop Layout (>=768px): horizontal layered -->
    <div class="arch-desktop">
      <template v-for="(layer, layerIdx) in layers" :key="layer.id">
        <div class="arch-layer">
          <div class="arch-layer-label">{{ layer.label }}</div>
          <div class="arch-layer-nodes">
            <div
              v-for="node in getNodesByLayer(layer.id)"
              :key="node.id"
              class="arch-node"
              :style="{ opacity: getNodeOpacity(node.id) }"
              @mouseenter="onNodeEnter(node.id)"
              @mouseleave="onNodeLeave"
            >
              <GlowNode :label="node.label" size="sm" />
            </div>
          </div>
        </div>
        <!-- Connection arrows between layers -->
        <div
          v-if="layerIdx < layers.length - 1"
          class="arch-connectors"
        >
          <div
            v-for="(conn, idx) in getConnectionsFromLayer(layer.id)"
            :key="idx"
            class="arch-connector"
            :style="{ opacity: getConnectionOpacity(conn) }"
          >
            <FlowLine :width="48" :height="3" />
            <span class="arch-arrow" aria-hidden="true">→</span>
          </div>
        </div>
      </template>
    </div>

    <!-- Mobile Layout (<768px): vertical arrangement -->
    <div class="arch-mobile">
      <template v-for="(layer, layerIdx) in layers" :key="layer.id">
        <div class="arch-mobile-layer">
          <div class="arch-layer-label">{{ layer.label }}</div>
          <div class="arch-mobile-nodes">
            <div
              v-for="node in getNodesByLayer(layer.id)"
              :key="node.id"
              class="arch-node"
              :style="{ opacity: getNodeOpacity(node.id) }"
              @mouseenter="onNodeEnter(node.id)"
              @mouseleave="onNodeLeave"
            >
              <GlowNode :label="node.label" size="sm" />
            </div>
          </div>
        </div>
        <!-- Vertical connectors between layers -->
        <div
          v-if="layerIdx < layers.length - 1"
          class="arch-mobile-connectors"
        >
          <div
            v-for="(conn, idx) in getConnectionsFromLayer(layer.id)"
            :key="idx"
            class="arch-mobile-connector"
            :style="{ opacity: getConnectionOpacity(conn) }"
          >
            <FlowLine :width="30" :height="3" />
            <span class="arch-arrow-down" aria-hidden="true">↓</span>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<style scoped>
.arch-diagram {
  width: 100%;
  padding: 1.5rem;
  background: rgba(17, 24, 39, 0.5);
  border: 1px solid rgba(0, 255, 170, 0.15);
  border-radius: 12px;
}

/* Desktop layout: hidden on mobile */
.arch-desktop {
  display: none;
}

@media (min-width: 768px) {
  .arch-desktop {
    display: flex;
    flex-direction: row;
    align-items: flex-start;
    justify-content: center;
    gap: 0.75rem;
  }
  .arch-mobile {
    display: none;
  }
}

.arch-layer {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.5rem;
  min-width: 80px;
}

.arch-layer-label {
  font-size: 0.7rem;
  color: rgba(0, 255, 170, 0.7);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  font-weight: 600;
  white-space: nowrap;
}

.arch-layer-nodes {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.5rem;
}

.arch-node {
  transition: opacity 0.3s ease;
  cursor: pointer;
  min-width: 80px;
  min-height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
}

/* Connectors between layers (desktop) */
.arch-connectors {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 0.25rem;
  padding-top: 1.5rem;
}

.arch-connector {
  display: flex;
  align-items: center;
  gap: 0.125rem;
  transition: opacity 0.3s ease;
}

.arch-arrow {
  color: rgba(0, 255, 170, 0.6);
  font-size: 0.875rem;
  line-height: 1;
}

/* Mobile layout */
.arch-mobile {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.75rem;
}

@media (min-width: 768px) {
  .arch-mobile {
    display: none;
  }
}

.arch-mobile-layer {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.5rem;
}

.arch-mobile-nodes {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 0.5rem;
}

.arch-mobile-connectors {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.125rem;
}

.arch-mobile-connector {
  display: flex;
  flex-direction: column;
  align-items: center;
  transition: opacity 0.3s ease;
}

.arch-arrow-down {
  color: rgba(0, 255, 170, 0.6);
  font-size: 0.875rem;
  line-height: 1;
}

/* Reduced motion */
@media (prefers-reduced-motion: reduce) {
  .arch-node,
  .arch-connector,
  .arch-mobile-connector {
    transition-duration: 0.01ms !important;
  }
}
</style>
